variable "project_name" {
  description = "Project name prefix"
  type        = string
}

variable "environment" {
  description = "Deployment environment"
  type        = string
}

variable "kms_key_id" {
  description = "Customer managed KMS key used to encrypt the secrets. Consumers therefore need kms:Decrypt on this key in addition to secretsmanager:GetSecretValue."
  type        = string
}

variable "recovery_window_in_days" {
  description = "Deletion recovery window. Set to 7 rather than the 30 day default so a secret name can be reused promptly if the layer is torn down and rebuilt; 0 would delete immediately with no recovery and is deliberately not used."
  type        = number
  default     = 7
}

############################################
# Redshift
############################################

variable "redshift_admin_username" {
  description = "Redshift Serverless admin username stored in the secret"
  type        = string
}

variable "redshift_admin_password" {
  description = "Redshift Serverless admin password stored in the secret. Sourced from terraform.tfvars, which is gitignored; never hardcode it and never surface it in an output."
  type        = string
  sensitive   = true
}

############################################
# RDS
############################################

variable "rds_master_username" {
  description = "PostgreSQL master username stored in the secret"
  type        = string
}

variable "rds_master_password" {
  description = "PostgreSQL master password stored in the secret. Generated by random_password at the root module, so it exists only in state and in this secret - never in tfvars, source, or an output."
  type        = string
  sensitive   = true
}
